#pragma once

/**
 * @file VFXCompiler.h
 * @brief VFX 编译器 — 将 VFXGraph 编译为 GPU Compute Shader (HLSL)
 *
 * 职责单一：接收 VFXGraph → 输出 HLSL 字符串 + 编译错误列表
 * 不依赖 ImGui / UI 层，可跨平台复用（未来可扩展为 GLSL/Metal 后端）
 *
 * 设计原则：
 *   - 纯函数：Compile(graph) → { code, errors }
 *   - 不持有任何状态，所有数据来自 VFXGraph
 *   - 错误信息包含 nodeId / pinId 便于 UI 高亮
 */

#include "VFXGraphCore.h"
#include <string>
#include <vector>
#include <sstream>

namespace Engine {
namespace VFX {

    // ============================================================
    // 编译结果
    // ============================================================
    struct VFXCompileResult {
        std::string hlslCode;
        std::vector<VFXCompileError> errors;
        bool success = false;

        // 编译统计
        uint32 instructionCount = 0;
        uint32 textureSampleCount = 0;
    };

    // ============================================================
    // 执行频率（用于语义校验）
    // ============================================================
    enum class ExecutionFrequency : uint8 {
        PerEmitter,     ///< 每 Emitter 执行一次（Spawn）
        PerParticle,    ///< 每个粒子每帧执行（Update）
        Once,           ///< 仅初始化执行一次（Initialize）
        Count
    };

    // ============================================================
    // VFX 编译器
    // ============================================================
    class VFXCompiler {
    public:
        VFXCompiler() = default;

        /// 编译 VFX 图 → HLSL Compute Shader
        static VFXCompileResult Compile(const VFXGraph* graph) {
            VFXCompileResult result;
            if (!graph) {
                VFXCompileError err;
                err.severity = VFXCompileError::Error;
                err.message = "VFXGraph is null.";
                result.errors.push_back(err);
                return result;
            }

            std::stringstream ss;

            // ── 1. 头 + 宏 ──
            ss << "// Generated by Game-Engine-Demo VFX Graph Compiler v1.0\n";
            ss << "#define PARTICLE_CAPACITY " << graph->GetParticleCapacity() << "\n\n";

            // ── 2. 粒子数据结构 ──
            ss << "struct ParticleData {\n";
            ss << "    float3 position;\n";
            ss << "    float3 velocity;\n";
            ss << "    float4 color;\n";
            ss << "    float size;\n";
            ss << "    float lifetime;\n";
            ss << "    float age;\n";
            ss << "    uint alive;\n";
            ss << "    float2 pad;\n";
            ss << "};\n\n";

            // ── 3. 常量缓冲区 ──
            ss << "cbuffer VFXParams : register(b0) {\n";
            ss << "    float4x4 _VFXViewProj;\n";
            ss << "    float _VFXDt;\n";
            ss << "    float _VFXTime;\n";
            ss << "    float2 _VFXPadding;\n";
            ss << "};\n\n";

            // ── 4. 黑板属性 ──
            for (auto& prop : graph->GetProperties()) {
                switch (prop.type) {
                    case VFXPinType::Float:
                        ss << "float _" << prop.name << ";\n"; break;
                    case VFXPinType::Float2:
                        ss << "float2 _" << prop.name << ";\n"; break;
                    case VFXPinType::Float3:
                        ss << "float3 _" << prop.name << ";\n"; break;
                    case VFXPinType::Color:
                        ss << "float4 _" << prop.name << ";\n"; break;
                    default: break;
                }
            }

            // ── 5. Emit 阶段 ──
            ss << "\n// ── Spawn: Emit ──\n";
            ss << "uint VFXEmit(uint aliveCount, uint maxCount, out ParticleData particle) {\n";
            ss << "    if (aliveCount >= maxCount) return 0;\n";
            ss << "    particle.alive = 1;\n";
            ss << "    particle.age = 0;\n";
            ss << "    particle.lifetime = 2.0;\n";
            ss << "    particle.position = 0;\n";
            ss << "    particle.velocity = 0;\n";
            ss << "    particle.color = float4(1,1,1,1);\n";
            ss << "    particle.size = 1.0;\n";

            // 从 Initialize Context 的 Block 生成初始化代码
            auto* initCtx = graph->GetContext(ContextType::Initialize);
            if (initCtx) {
                for (uint32 bid : initCtx->blockIds) {
                    auto* block = graph->GetBlock(bid);
                    if (block && block->IsEnabled()) {
                        std::unordered_map<uint32, std::string> pinOutputs;
                        ss << "    // " << block->GetName() << "\n";
                        ss << "    " << block->GenerateHLSL(pinOutputs) << "\n";
                    }
                }
            }

            ss << "    return 1;\n";
            ss << "}\n";

            // ── 6. Update 阶段 ──
            ss << "\n// ── Update ──\n";
            ss << "void VFXUpdate(inout ParticleData p, float dt) {\n";
            ss << "    p.age += dt;\n";
            ss << "    if (p.age >= p.lifetime) { p.alive = 0; return; }\n";
            ss << "    float t = p.age / p.lifetime;\n";

            auto* updateCtx = graph->GetContext(ContextType::Update);
            if (updateCtx) {
                for (uint32 bid : updateCtx->blockIds) {
                    auto* block = graph->GetBlock(bid);
                    if (block && block->IsEnabled()) {
                        std::unordered_map<uint32, std::string> pinOutputs;
                        ss << "    // Block: " << block->GetName() << "\n";
                        ss << "    " << block->GenerateHLSL(pinOutputs) << "\n";
                        result.instructionCount++;
                    }
                }
            }

            ss << "}\n";

            // ── 7. 主 Compute Shader ──
            ss << "\n// ── Main Compute Shader ──\n";
            ss << "RWStructuredBuffer<ParticleData> _VFXBuffer : register(u0);\n\n";
            ss << "[numthreads(64, 1, 1)]\n";
            ss << "void VFXMainCS(uint3 id : SV_DispatchThreadID) {\n";
            ss << "    uint idx = id.x;\n";
            ss << "    if (idx >= PARTICLE_CAPACITY) return;\n";
            ss << "    ParticleData p = _VFXBuffer[idx];\n";
            ss << "    if (!p.alive) return;\n";
            ss << "    VFXUpdate(p, _VFXDt);\n";
            ss << "    _VFXBuffer[idx] = p;\n";
            ss << "}\n";

            // ── 8. Billboard VS/PS ──
            ss << "\n// ── Billboard Vertex Shader ──\n";
            ss << "struct VSOutput {\n";
            ss << "    float4 position : SV_Position;\n";
            ss << "    float2 uv : TEXCOORD0;\n";
            ss << "    float4 color : COLOR;\n";
            ss << "};\n\n";
            ss << "VSOutput VFXBillboardVS(uint vertexId : SV_VertexID, uint instanceId : SV_InstanceID) {\n";
            ss << "    ParticleData p = _VFXBuffer[instanceId];\n";
            ss << "    VSOutput o;\n";
            ss << "    o.position = float4(p.position, 1);\n";
            ss << "    o.uv = float2(0,0);\n";
            ss << "    o.color = p.color;\n";
            ss << "    return o;\n";
            ss << "}\n\n";
            ss << "float4 VFXBillboardPS(VSOutput i) : SV_Target {\n";
            ss << "    return i.color;\n";
            ss << "}\n";

            result.hlslCode = ss.str();
            result.success = result.errors.empty();
            return result;
        }

        /// 计算 Block 的执行频率（根据所属 Context）
        static ExecutionFrequency GetBlockFrequency(const VFXBlock* block, const VFXGraph* graph) {
            if (!block || !graph) return ExecutionFrequency::PerParticle;

            for (auto& ctx : graph->GetContexts()) {
                for (uint32 bid : ctx.blockIds) {
                    if (bid == block->GetId()) {
                        switch (ctx.type) {
                            case ContextType::Spawn:      return ExecutionFrequency::PerEmitter;
                            case ContextType::Initialize:  return ExecutionFrequency::Once;
                            case ContextType::Update:      return ExecutionFrequency::PerParticle;
                            case ContextType::Output:      return ExecutionFrequency::PerParticle;
                            default:                       return ExecutionFrequency::PerParticle;
                        }
                    }
                }
            }
            return ExecutionFrequency::PerParticle;
        }

        /// 验证连接是否合法（含跨 Context 时序校验）
        static bool ValidateLink(const VFXGraph* graph,
                                  const VFXPin& outPin, const VFXPin& inPin,
                                  std::string& outReason) {
            if (!graph) return false;

            // 1. 基础校验
            if (outPin.direction == inPin.direction) {
                outReason = "Cannot connect two pins of same direction.";
                return false;
            }
            if (outPin.direction != PinDirection::Output) {
                outReason = "Source pin must be an output.";
                return false;
            }
            if (inPin.direction != PinDirection::Input) {
                outReason = "Target pin must be an input.";
                return false;
            }
            if (outPin.nodeId == inPin.nodeId) {
                outReason = "Cannot connect a node to itself.";
                return false;
            }

            // 2. 类型兼容检查
            if (outPin.type != inPin.type &&
                outPin.type != VFXPinType::DynamicVector &&
                inPin.type != VFXPinType::DynamicVector &&
                outPin.type != VFXPinType::ParticleData &&
                inPin.type != VFXPinType::ParticleData)
            {
                outReason = "Pin type mismatch.";
                return false;
            }

            // 3. 跨 Context 时序校验（VFX Graph 核心语义）
            auto* outBlock = graph->GetBlock(outPin.nodeId);
            auto* inBlock = graph->GetBlock(inPin.nodeId);
            if (!outBlock || !inBlock) return false;

            ExecutionFrequency outFreq = GetBlockFrequency(outBlock, graph);
            ExecutionFrequency inFreq = GetBlockFrequency(inBlock, graph);

            // Spawn (PerEmitter) 的数据不能输入到 Update (PerParticle)
            // 因为 Spawn 在 CPU 端执行，Update 在 GPU 端执行
            if (outFreq == ExecutionFrequency::PerEmitter &&
                inFreq == ExecutionFrequency::PerParticle) {
                // 允许 ParticleData 类型的传递（这是隐式的 spawn→simulate 数据流）
                if (outPin.type != VFXPinType::ParticleData) {
                    outReason = "Cannot connect Per-Emitter data to Per-Particle input. "
                                "Use ParticleData flow instead.";
                    return false;
                }
            }

            // Update 阶段的数据不能连回 Spawn（时间悖论）
            if (outFreq > inFreq) {
                outReason = "Cannot connect data back in time (e.g., Update -> Spawn).";
                return false;
            }

            return true;
        }
    };

}} // namespace Engine::VFX